# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 300 
  config.vm.graceful_halt_timeout = 120

  config.vm.box = ""

  # enable RDP access
  config.vm.network :forwarded_port, guest: 3389, host: 3389
end
