# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrantfile for testing new Ubuntu install
# provisioning in case I ever need to do a new
# workstation from scratch

Vagrant.configure("2") do |config|
  config.vm.define "doppel" do |config| 
    config.vm.box = "ubuntu/bionic64"

    config.vm.network "private_network", ip: "192.168.1.88"
    
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      ln -s /usr/bin/python3.6 /usr/bin/python 

      mkdir -p /home/vagrant/repos/
      git -C /home/vagrant/repos/ clone https://github.com/dolmengate/wkstn-prov.git

      (cd /home/vagrant/repos/wkstn-prov/ ; ansible-playbook wkstn-prov.yml)
    SHELL

  end
end
